# Generated by Django 3.2.5 on 2021-07-22 19:59

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tasks',
            fields=[
                ('tid', models.AutoField(primary_key=True, serialize=False)),
                ('task_title', models.CharField(blank=True, max_length=200, null=True, validators=[django.core.validators.MinLengthValidator(4)])),
                ('task_description', models.TextField(blank=True, max_length=2000, null=True)),
                ('task_pic', models.FileField(blank=True, null=True, upload_to='Images/license_img/')),
                ('create_time_stamp', models.DateTimeField(auto_now_add=True, null=True)),
                ('uid', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
