# Generated by Django 3.2.5 on 2021-07-22 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0003_auto_20210722_2119'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tasks',
            name='task_pic',
            field=models.ImageField(blank=True, null=True, upload_to='images'),
        ),
    ]
